name: Deploy Iris API

on:
  push:
    branches:
      - dev-docker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: eternal-cycling-463617-f7

      - name: Authenticate Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Configure GKE credentials
        run: |
          gcloud container clusters get-credentials iris-cluster-6 \
            --zone us-central1 \
            --project eternal-cycling-463617-f7

      - name: Run deployment script
        run: ./cml_deploy.sh
