name: Sanity test

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up CML
        uses: iterative/setup-cml@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install 'dvc-gs'  # Enable GCS support for DVC

      - name: Authenticate to Google Cloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-key.json
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project eternal-cycling-463617-f7

      - name: Pull data with DVC
        run: dvc pull

      - name: Run unit tests
        run: |
          python -m w4a_test 2>&1 | tee test_output.txt

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### Test Output" > report.md
          echo "\`\`\`" >> report.md
          cat test_output.txt >> report.md
          echo "\`\`\`" >> report.md

          echo "### Metrics from Training" >> report.md
          cat artifacts/metrics.csv >> report.md

          cml comment create --publish report.md
